#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_TRAY 101

// Dialogs
#define IDD_MAIN 100
#define IDD_SETTINGS_GENERAL 101
#define IDD_SETTINGS_MEMORY 102
#define IDD_SETTINGS_APPEARANCE 103
#define IDD_SETTINGS_TRAY 104
#define IDD_SETTINGS_ADVANCED 105

// Main Dlg
#define IDC_LISTVIEW 102
#define IDC_CLEAN 103

#define IDC_TITLE_1 104
#define IDC_TITLE_2 105
#define IDC_TITLE_3 106
#define IDC_TITLE_4 107
#define IDC_TITLE_5 108
#define IDC_TITLE_6 109
#define IDC_TITLE_7 110
#define IDC_TITLE_8 111
#define IDC_TITLE_9 112

#define IDC_ALWAYSONTOP_CHK 113
#define IDC_LOADONSTARTUP_CHK 114
#define IDC_STARTMINIMIZED_CHK 115
#define IDC_SKIPUACWARNING_CHK 116
#define IDC_REDUCTCONFIRMATION_CHK 117
#define IDC_CHECKUPDATES_CHK 118

#define IDC_LANGUAGE_HINT 119
#define IDC_LANGUAGE 120

#define IDC_REGIONS 121

#define IDC_AUTOREDUCTENABLE_CHK 122
#define IDC_AUTOREDUCTVALUE_CTRL 123
#define IDC_AUTOREDUCTVALUE 124

#define IDC_AUTOREDUCTINTERVALENABLE_CHK 125
#define IDC_AUTOREDUCTINTERVALVALUE_CTRL 126
#define IDC_AUTOREDUCTINTERVALVALUE 127

#define IDC_HOTKEY_CLEAN_CHK 128
#define IDC_HOTKEY_CLEAN 129

#define IDC_TRAYUSETRANSPARENCY_CHK 130
#define IDC_TRAYSHOWBORDER_CHK 131
#define IDC_TRAYROUNDCORNERS_CHK 132
#define IDC_TRAYCHANGEBG_CHK 133
#define IDC_TRAYUSEANTIALIASING_CHK 134

#define IDC_FONT_HINT 135
#define IDC_FONT 136

#define IDC_COLORS 137

#define IDC_TRAYLEVELWARNING_HINT 138
#define IDC_TRAYLEVELWARNING_CTRL 139
#define IDC_TRAYLEVELWARNING 140

#define IDC_TRAYLEVELDANGER_HINT 141
#define IDC_TRAYLEVELDANGER_CTRL 142
#define IDC_TRAYLEVELDANGER 143

#define IDC_TRAYACTIONSC_HINT 144
#define IDC_TRAYACTIONSC 145

#define IDC_TRAYACTIONMC_HINT 146
#define IDC_TRAYACTIONMC 147

#define IDC_NOTIFICATIONSOUND_CHK 148

#define IDC_SHOW_CLEAN_RESULT_CHK 149

#define IDC_ALLOWSTANDBYLISTCLEANUP_CHK 150
#define IDC_LOGRESULTS_CHK 151

// Main Menu
#define IDM_SETTINGS 152
#define IDM_EXIT 153
#define IDM_ALWAYSONTOP_CHK 154
#define IDM_LOADONSTARTUP_CHK 155
#define IDM_USEDARKTHEME 156
#define IDM_STARTMINIMIZED_CHK 157
#define IDM_REDUCTCONFIRMATION_CHK 158
#define IDM_SKIPUACWARNING_CHK 159
#define IDM_CHECKUPDATES_CHK 160

#define IDM_WEBSITE 161
#define IDM_CHECKUPDATES 162
#define IDM_ABOUT 163

// Tray Menu
#define IDM_TRAY_SHOW 164
#define IDM_TRAY_CLEAN 165
#define IDM_TRAY_DISABLE_1 166
#define IDM_TRAY_DISABLE_2 167
#define IDM_TRAY_SETTINGS 168
#define IDM_TRAY_WEBSITE 169
#define IDM_TRAY_ABOUT 170
#define IDM_TRAY_EXIT 171

#define IDM_WORKINGSET_CHK 172
#define IDM_SYSTEMFILECACHE_CHK 173
#define IDM_MODIFIEDFILECACHE_CHK 174
#define IDM_MODIFIEDLIST_CHK 175
#define IDM_STANDBYLIST_CHK 176
#define IDM_STANDBYLISTPRIORITY0_CHK 177
#define IDM_REGISTRYCACHE_CHK 178
#define IDM_COMBINEMEMORYLISTS_CHK 179

#define IDM_CLEAN_WORKINGSET 180
#define IDM_CLEAN_SYSTEMFILECACHE 181
#define IDM_CLEAN_MODIFIEDFILECACHE 182
#define IDM_CLEAN_MODIFIEDLIST 183
#define IDM_CLEAN_STANDBYLIST 184
#define IDM_CLEAN_STANDBYLISTPRIORITY0 185
#define IDM_CLEAN_REGISTRYCACHE 186
#define IDM_CLEAN_COMBINEMEMORYLISTS 187

#define IDX_LANGUAGE 1000
#define IDX_TRAY_POPUP_1 2000
#define IDX_TRAY_POPUP_2 3000

// Strings
#define IDS_UPDATE_NO 1
#define IDS_UPDATE_YES 2

#define IDS_FILE 3
#define IDS_SETTINGS 4
#define IDS_EXIT 5
#define IDS_LANGUAGE 6
#define IDS_HELP 7
#define IDS_WEBSITE 8
#define IDS_CHECKUPDATES 9
#define IDS_ABOUT 10
#define IDS_DONATE 11

#define IDS_TRAY_SHOW 12
#define IDS_TRAY_DISABLE 13
#define IDS_TRAY_POPUP_1 14
#define IDS_TRAY_POPUP_2 15
#define IDS_TRAY_POPUP_3 16

#define IDS_CLEAN 17

#define IDS_GROUP_1 18
#define IDS_GROUP_2 19
#define IDS_GROUP_3 20

#define IDS_ITEM_1 21
#define IDS_ITEM_2 22
#define IDS_ITEM_3 23

#define IDS_SETTINGS_GENERAL 24
#define IDS_SETTINGS_MEMORY 25
#define IDS_SETTINGS_APPEARANCE 26
#define IDS_SETTINGS_TRAY 27

#define IDS_CLOSE 28

#define IDS_TITLE_1 29
#define IDS_TITLE_2 30
#define IDS_TITLE_3 31
#define IDS_TITLE_4 32
#define IDS_TITLE_5 33
#define IDS_TITLE_6 34
#define IDS_TITLE_7 35
#define IDS_TITLE_8 36
#define IDS_TITLE_9 37

#define IDS_ALWAYSONTOP_CHK 38
#define IDS_LOADONSTARTUP_CHK 39
#define IDS_STARTMINIMIZED_CHK 40
#define IDS_REDUCTCONFIRMATION_CHK 41
#define IDS_SKIPUACWARNING_CHK 42
#define IDS_CHECKUPDATES_CHK 43

#define IDS_LANGUAGE_HINT 44

#define IDS_WORKINGSET_CHK 45
#define IDS_SYSTEMWORKINGSET_CHK 46
#define IDS_STANDBYLISTPRIORITY0_CHK 47
#define IDS_STANDBYLIST_CHK 48
#define IDS_MODIFIEDLIST_CHK 49
#define IDS_COMBINEMEMORYLISTS_CHK 50

#define IDS_AUTOREDUCTENABLE_CHK 51
#define IDS_AUTOREDUCTINTERVALENABLE_CHK 52

#define IDS_HOTKEY_CLEAN_CHK 53

#define IDS_TRAYUSETRANSPARENCY_CHK 54
#define IDS_TRAYSHOWBORDER_CHK 55
#define IDS_TRAYROUNDCORNERS_CHK 56
#define IDS_TRAYCHANGEBG_CHK 57
#define IDS_TRAYUSEANTIALIASING_CHK 58

#define IDS_FONT_HINT 59
#define IDS_COLOR_TEXT_HINT 60
#define IDS_COLOR_BACKGROUND_HINT 61
#define IDS_COLOR_WARNING_HINT 62
#define IDS_COLOR_DANGER_HINT 63

#define IDS_TRAYLEVELWARNING_HINT 64
#define IDS_TRAYLEVELDANGER_HINT 65

#define IDS_TRAYACTIONSC_HINT 66
#define IDS_TRAYACTIONMC_HINT 67

#define IDS_TRAY_ACTION_1 68
#define IDS_TRAY_ACTION_2 69
#define IDS_TRAY_ACTION_3 70

#define IDS_SHOW_CLEAN_RESULT_CHK 71

#define IDS_QUESTION 72
#define IDS_QUESTION_WARNING 73
#define IDS_QUESTION_FLAG_CHK 74

#define IDS_STATUS_CLEANED 75
#define IDS_STATUS_NOPRIVILEGES 76

#define IDS_UPDATE_DOWNLOAD 77
#define IDS_UPDATE_DONE 78
#define IDS_UPDATE_ERROR 79
#define IDS_UPDATE_INIT 80
#define IDS_UPDATE_INSTALL 81

#define IDS_RESET 82
#define IDS_QUESTION_RESET 83

#define IDS_NOTIFICATIONSOUND_CHK 84

#define IDS_TITLE_ADVANCED 85

#define IDS_VIEW 86

#define IDS_USEDARKTHEME 87

#define IDS_UPDATE_SPEED 88

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
