#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_TRAY 101

// Dialogs
#define IDD_MAIN 100
#define IDD_SETTINGS 101
#define IDD_SETTINGS_GENERAL 102
#define IDD_SETTINGS_MEMORY 103
#define IDD_SETTINGS_APPEARANCE 104
#define IDD_SETTINGS_TRAY 105

// Main Dlg
#define IDC_LISTVIEW 102
#define IDC_CLEAN 103

// Settings Dlg
#define IDC_NAV 104
#define IDC_CLOSE 105

#define IDC_TITLE_1 106
#define IDC_TITLE_2 107
#define IDC_TITLE_3 108
#define IDC_TITLE_4 109
#define IDC_TITLE_5 110
#define IDC_TITLE_6 111
#define IDC_TITLE_7 112
#define IDC_TITLE_8 113
#define IDC_TITLE_9 114

#define IDC_ALWAYSONTOP_CHK 115
#define IDC_LOADONSTARTUP_CHK 116
#define IDC_SKIPUACWARNING_CHK 117
#define IDC_REDUCTCONFIRMATION_CHK 118
#define IDC_CHECKUPDATES_CHK 119

#define IDC_LANGUAGE_HINT 120
#define IDC_LANGUAGE 121

#define IDC_WORKINGSET_CHK 122
#define IDC_SYSTEMWORKINGSET_CHK 123
#define IDC_STANDBYLISTPRIORITY0_CHK 124
#define IDC_STANDBYLIST_CHK 125
#define IDC_MODIFIEDLIST_CHK 126
#define IDC_COMBINEMEMORYLISTS_CHK 127

#define IDC_AUTOREDUCTENABLE_CHK 128
#define IDC_AUTOREDUCTVALUE_CTRL 129
#define IDC_AUTOREDUCTVALUE 130

#define IDC_AUTOREDUCTINTERVALENABLE_CHK 131
#define IDC_AUTOREDUCTINTERVALVALUE_CTRL 132
#define IDC_AUTOREDUCTINTERVALVALUE 133

#define IDC_HOTKEY_CLEAN_CHK 134
#define IDC_HOTKEY_CLEAN 135

#define IDC_TRAYUSETRANSPARENCY_CHK 136
#define IDC_TRAYSHOWBORDER_CHK 137
#define IDC_TRAYROUNDCORNERS_CHK 138
#define IDC_TRAYCHANGEBG_CHK 139
#define IDC_TRAYUSEANTIALIASING_CHK 140

#define IDC_FONT_HINT 141
#define IDC_FONT 142

#define IDC_COLOR_TEXT_HINT 143
#define IDC_COLOR_TEXT 144

#define IDC_COLOR_BACKGROUND_HINT 145
#define IDC_COLOR_BACKGROUND 146

#define IDC_COLOR_WARNING_HINT 147
#define IDC_COLOR_WARNING 148

#define IDC_COLOR_DANGER_HINT 149
#define IDC_COLOR_DANGER 150

#define IDC_TRAYLEVELWARNING_HINT 151
#define IDC_TRAYLEVELWARNING_CTRL 152
#define IDC_TRAYLEVELWARNING 153

#define IDC_TRAYLEVELDANGER_HINT 154
#define IDC_TRAYLEVELDANGER_CTRL 155
#define IDC_TRAYLEVELDANGER 156

#define IDC_TRAYACTIONDC_HINT 157
#define IDC_TRAYACTIONDC 158

#define IDC_TRAYACTIONMC_HINT 159
#define IDC_TRAYACTIONMC 160

#define IDC_SHOW_CLEAN_RESULT_CHK 161

// Main Menu
#define IDM_SETTINGS 162
#define IDM_EXIT 163
#define IDM_ALWAYSONTOP_CHK 164
#define IDM_CHECKUPDATES_CHK 165

#define IDM_WEBSITE 166
#define IDM_CHECKUPDATES 167
#define IDM_ABOUT 168

// Tray Menu
#define IDM_TRAY_SHOW 169
#define IDM_TRAY_CLEAN 170
#define IDM_TRAY_DISABLE_1 171
#define IDM_TRAY_DISABLE_2 172
#define IDM_TRAY_SETTINGS 173
#define IDM_TRAY_WEBSITE 174
#define IDM_TRAY_ABOUT 175
#define IDM_TRAY_EXIT 176

#define IDM_WORKINGSET_CHK 177
#define IDM_SYSTEMWORKINGSET_CHK 178
#define IDM_STANDBYLISTPRIORITY0_CHK 179
#define IDM_STANDBYLIST_CHK 180
#define IDM_MODIFIEDLIST_CHK 181
#define IDM_COMBINEMEMORYLISTS_CHK 182

#define IDX_LANGUAGE 1000
#define IDX_TRAY_POPUP_1 2000
#define IDX_TRAY_POPUP_2 3000

// Strings
#define IDS_UPDATE_NO 1
#define IDS_UPDATE_YES 2

#define IDS_FILE 3
#define IDS_SETTINGS 4
#define IDS_EXIT 5
#define IDS_LANGUAGE 6
#define IDS_HELP 7
#define IDS_WEBSITE 8
#define IDS_CHECKUPDATES 9
#define IDS_ABOUT 10
#define IDS_DONATE 11

#define IDS_TRAY_SHOW 12
#define IDS_TRAY_DISABLE 13
#define IDS_TRAY_POPUP_1 14
#define IDS_TRAY_POPUP_2 15
#define IDS_TRAY_POPUP_3 16

#define IDS_CLEAN 17

#define IDS_GROUP_1 18
#define IDS_GROUP_2 19
#define IDS_GROUP_3 20

#define IDS_ITEM_1 21
#define IDS_ITEM_2 22
#define IDS_ITEM_3 23

#define IDS_SETTINGS_GENERAL 24
#define IDS_SETTINGS_MEMORY 25
#define IDS_SETTINGS_APPEARANCE 26
#define IDS_SETTINGS_TRAY 27

#define IDS_CLOSE 28

#define IDS_TITLE_1 29
#define IDS_TITLE_2 30
#define IDS_TITLE_3 31
#define IDS_TITLE_4 32
#define IDS_TITLE_5 33
#define IDS_TITLE_6 34
#define IDS_TITLE_7 35
#define IDS_TITLE_8 36
#define IDS_TITLE_9 37

#define IDS_ALWAYSONTOP_CHK 38
#define IDS_LOADONSTARTUP_CHK 39
#define IDS_REDUCTCONFIRMATION_CHK 40
#define IDS_SKIPUACWARNING_CHK 41
#define IDS_CHECKUPDATES_CHK 42

#define IDS_LANGUAGE_HINT 43

#define IDS_WORKINGSET_CHK 44
#define IDS_SYSTEMWORKINGSET_CHK 45
#define IDS_STANDBYLISTPRIORITY0_CHK 46
#define IDS_STANDBYLIST_CHK 47
#define IDS_MODIFIEDLIST_CHK 48
#define IDS_COMBINEMEMORYLISTS_CHK 49

#define IDS_AUTOREDUCTENABLE_CHK 50
#define IDS_AUTOREDUCTINTERVALENABLE_CHK 51

#define IDS_HOTKEY_CLEAN_CHK 52

#define IDS_TRAYUSETRANSPARENCY_CHK 53
#define IDS_TRAYSHOWBORDER_CHK 54
#define IDS_TRAYROUNDCORNERS_CHK 55
#define IDS_TRAYCHANGEBG_CHK 56
#define IDS_TRAYUSEANTIALIASING_CHK 57

#define IDS_FONT_HINT 58
#define IDS_COLOR_TEXT_HINT 59
#define IDS_COLOR_BACKGROUND_HINT 60
#define IDS_COLOR_WARNING_HINT 61
#define IDS_COLOR_DANGER_HINT 62

#define IDS_TRAYLEVELWARNING_HINT 63
#define IDS_TRAYLEVELDANGER_HINT 64

#define IDS_TRAYACTIONDC_HINT 65
#define IDS_TRAYACTIONMC_HINT 66

#define IDS_TRAY_ACTION_1 67
#define IDS_TRAY_ACTION_2 68
#define IDS_TRAY_ACTION_3 69

#define IDS_SHOW_CLEAN_RESULT_CHK 70

#define IDS_QUESTION 71
#define IDS_QUESTION_WARNING 72
#define IDS_QUESTION_FLAG_CHK 73

#define IDS_STATUS_CLEANED 74
#define IDS_STATUS_NOPRIVILEGES 75

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
